<?php

define("ENABLE_LOG",true);

//define("GOOGLE_API_KEY","AIzaSyDklZABjWfNoMGyIA1z-DQkrQQ7uqE9n1k");
define("GOOGLE_API_KEY","AIzaSyCcA3y-r-JUTn-hEC_3ysabEJRfgSqAqTw");

define("ROUTE_API","google");//baidu , CUSTOM_TSP

define("DRIVING_TIME_GOOGLE_OFFSET_RATE",1);

define("PROGRESS_TIMEOUT_SECOND",15);
define("WAYPOINT_MAX",4);

define("ROUTE_API_STATUS_PROGRESS",'in progress');
define("ROUTE_API_STATUS_FAILURE",'failure');
define("ROUTE_API_STATUS_SUCCESS",'success');


define("ROUTE_API_ERROR_MSG_WAYPOINT_INVAILD",'WAYPOINT_INVAILD');
define("ROUTE_API_ERROR_MSG_PARAMS_INVAILD",'PARAMS_INVAILD');
define("ROUTE_API_ERROR_MSG_NO_RETURN",'NO_RETURN');
define("ROUTE_API_ERROR_MSG_RETURN_ERROR",'RETURN_ERROR');
define("ROUTE_API_ERROR_MSG_TOKEN_NOT_EXIST",'TOKEN_NOT_EXIST');
define("ROUTE_API_ERROR_MSG_TIMEOUT",'TIMEOUT');


define("GET_TOKEN_ERROR_MSG_ROBOT_CHECK",'ROBOT_CHECK');
define("GET_TOKEN_ERROR_MSG_NO_WAYPOINT",'NO_WAYPOINT');
define("GET_TOKEN_ERROR_MSG_OVER_WAYPOINT_MAX",'OVER_WAYPOINT_MAX');
define("GET_TOKEN_ERROR_MSG_WAYPOINT_MIN",'WAYPOINT_MIN');
define("GET_TOKEN_ERROR_MSG_WAYPOINT_FORMAT_ERROR",'WAYPOINT_FORMAT_ERROR');




